name: metocean-stats
channels:
  - conda-forge
dependencies:
  - python=>3.9
  - matplotlib>=3.1
  - numpy>=1.17
  - pandas
  - pip
  - scipy
  - pytest
  - windrose
  - seaborn>=0.12.2
  - metocean-api
  - basemap
  - calendar
  - math
  - shutil
  - os
  - dataframe_image
  - netCDF4
  - pickle
  - pyextremes
  - datetime
